version: '3.8'

services:
  bd:
    image: postgres:16
    container_name: database_news_portal
    restart: "no"
    ports: 
      - "5633:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - news_portal_network
  minio:
    image: minio/minio:latest
    container_name: minio_news_portal
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio_data:/data
    command: ["server","/data","--console-address",":9001"]
    networks:
      - news_portal_network
volumes:
  postgres_data:
  minio_data:
networks:
  news_portal_network:
    driver: bridge  